export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

import About from "@/components/About";

export default function AboutMyPage() {
  return (
    <div>
      <About />
    </div>
  );
}
